
# Paper-https://arxiv.org/pdf/1503.08895.pdf

# Question: Implement the above research paper-"End to End Memory Networks"


# Step 1: Load the dataset

In [ ]:
import pickle
import numpy as np

In [ ]:
with open("train.txt", "rb") as fp:  
    train_data =  pickle.load(fp)

In [ ]:
with open("test.txt", "rb") as fp:  
    test_data =  pickle.load(fp)

In [ ]:
train_data


[(['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.'],
  ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.',
   'Sandra',
   'went',
   'to',
   'the',
   'kitchen',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'bathroom',
   '.'],
  ['Is', 'Daniel', 'in', 'the', '

In [ ]:
train_data[0] 

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [ ]:
' '.join(train_data[0][0]) 

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [ ]:
' '.join(train_data[0][1]) 

'Is Sandra in the hallway ?'

In [ ]:
train_data[0][2]

'no'

# Step 2: Prepare Vocabulary

In [ ]:
vocab #including yes and no-38 words

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

## Step 3: Generate Indexes

-----------

In [ ]:
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

{'.': 22,
 '?': 21,
 'apple': 28,
 'back': 1,
 'bathroom': 30,
 'bedroom': 11,
 'daniel': 36,
 'discarded': 33,
 'down': 14,
 'dropped': 8,
 'football': 15,
 'garden': 4,
 'got': 5,
 'grabbed': 23,
 'hallway': 34,
 'in': 17,
 'is': 6,
 'john': 10,
 'journeyed': 9,
 'kitchen': 31,
 'left': 12,
 'mary': 13,
 'milk': 32,
 'moved': 2,
 'no': 7,
 'office': 16,
 'picked': 26,
 'put': 24,
 'sandra': 35,
 'the': 18,
 'there': 3,
 'to': 25,
 'took': 20,
 'travelled': 37,
 'up': 19,
 'went': 27,
 'yes': 29}

In [ ]:
#Train content with indexes

[[13, 2, 25, 18, 30, 22, 35, 9, 25, 18, 11, 22], [13, 2, 25, 18, 30, 22, 35, 9, 25, 18, 11, 22, 13, 27, 1, 25, 18, 11, 22, 36, 27, 1, 25, 18, 34, 22], [13, 2, 25, 18, 30, 22, 35, 9, 25, 18, 11, 22, 13, 27, 1, 25, 18, 11, 22, 36, 27, 1, 25, 18, 34, 22, 35, 27, 25, 18, 31, 22, 36, 27, 1, 25, 18, 30, 22], [13, 2, 25, 18, 30, 22, 35, 9, 25, 18, 11, 22, 13, 27, 1, 25, 18, 11, 22, 36, 27, 1, 25, 18, 34, 22, 35, 27, 25, 18, 31, 22, 36, 27, 1, 25, 18, 30, 22, 36, 26, 19, 18, 15, 3, 22, 36, 27, 25, 18, 11, 22], [13, 2, 25, 18, 30, 22, 35, 9, 25, 18, 11, 22, 13, 27, 1, 25, 18, 11, 22, 36, 27, 1, 25, 18, 34, 22, 35, 27, 25, 18, 31, 22, 36, 27, 1, 25, 18, 30, 22, 36, 26, 19, 18, 15, 3, 22, 36, 27, 25, 18, 11, 22, 10, 37, 25, 18, 16, 22, 35, 27, 25, 18, 4, 22], [35, 5, 18, 15, 3, 22, 13, 27, 25, 18, 11, 22], [35, 5, 18, 15, 3, 22, 13, 27, 25, 18, 11, 22, 36, 5, 18, 28, 3, 22, 35, 37, 25, 18, 34, 22], [35, 5, 18, 15, 3, 22, 13, 27, 25, 18, 11, 22, 36, 5, 18, 28, 3, 22, 35, 37, 25, 18, 34, 22, 35, 2,

In [ ]:
#train Questions

[['Is', 'Sandra', 'in', 'the', 'hallway', '?'], ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'], ['Is', 'Daniel', 'in', 'the', 'office', '?'], ['Is', 'Daniel', 'in', 'the', 'bedroom', '?'], ['Is', 'Daniel', 'in', 'the', 'bedroom', '?'], ['Is', 'Mary', 'in', 'the', 'bedroom', '?'], ['Is', 'Sandra', 'in', 'the', 'office', '?'], ['Is', 'Sandra', 'in', 'the', 'bathroom', '?'], ['Is', 'Sandra', 'in', 'the', 'bathroom', '?'], ['Is', 'Mary', 'in', 'the', 'kitchen', '?'], ['Is', 'Sandra', 'in', 'the', 'office', '?'], ['Is', 'Mary', 'in', 'the', 'hallway', '?'], ['Is', 'Mary', 'in', 'the', 'hallway', '?'], ['Is', 'Mary', 'in', 'the', 'hallway', '?'], ['Is', 'Mary', 'in', 'the', 'garden', '?'], ['Is', 'Sandra', 'in', 'the', 'office', '?'], ['Is', 'Sandra', 'in', 'the', 'bathroom', '?'], ['Is', 'Sandra', 'in', 'the', 'kitchen', '?'], ['Is', 'Mary', 'in', 'the', 'bedroom', '?'], ['Is', 'Mary', 'in', 'the', 'kitchen', '?'], ['Is', 'Daniel', 'in', 'the', 'bedroom', '?'], ['Is', 'Sandra', 'in', 'the',

### Step 4: Vectorization

In [ ]:
#inputs vectorized

array([[ 0,  0,  0, ..., 18, 11, 22],
       [ 0,  0,  0, ..., 18,  4, 22],
       [ 0,  0,  0, ..., 18,  4, 22],
       ...,
       [ 0,  0,  0, ..., 18, 28, 22],
       [ 0,  0,  0, ..., 18,  4, 22],
       [ 0,  0,  0, ..., 28,  3, 22]], dtype=int32)

In [ ]:
#Questions vectorized

array([[ 6, 10, 17, 18, 31, 21],
       [ 6, 10, 17, 18, 31, 21],
       [ 6, 10, 17, 18,  4, 21],
       ...,
       [ 6, 13, 17, 18, 11, 21],
       [ 6, 35, 17, 18,  4, 21],
       [ 6, 13, 17, 18,  4, 21]], dtype=int32)

In [ ]:
# Questions shape

(1000, 6)

In [ ]:
# Vectorized Answers

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
 #answer can be anything from 38 unique vocabulary words in train/test

(1000, 38)

In [ ]:
# No other answers other than Yes/No

array([  0.,   0.,   0.,   0.,   0.,   0.,   0., 503.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0., 497.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [ ]:
# index for "yes"

29

In [ ]:
# index for "No"

7

## Step 5: Build the Model

In [ ]:
from keras.models import Sequential, Model
from keras.layers.embeddings import Embedding
from keras.layers import Input, Activation, Dense, Permute, Dropout
from keras.layers import add, dot, concatenate
from keras.layers import LSTM

#### Ensure that padding is done for content and questions

## 5.1. Encoders

### Input Encoder m

In [ ]:
# Input gets embedded to a sequence of vectors

# Use sequential() and Embedding() from keras


### 5.2 Input Encoder c

In [ ]:
# encode the input of size questions max_length

# Use sequential() and Embedding() from keras


### 5.3 Question Encoder

In [ ]:
# encode the questions

# Use sequential() and Embedding() from keras


### 5.4 Encode the Sequences

In [ ]:
# Specify the maximum input and question dimensions

##### 5.5. Use dot product 

#### 5.6 Add this match matrix with the second input vector sequence

#### 5.7. Concatenate and create LSTM network at the end and the model should have the following configuration

In [ ]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 156)]        0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 6)]          0           []                               
                                                                                                  
 sequential (Sequential)        (None, None, 64)     2432        ['input_1[0][0]']                
                                                                                                  
 sequential_2 (Sequential)      (None, 6, 64)        2432        ['input_2[0][0]']                
                                                                                              

# 5.8. Train

In [ ]:
#train

Epoch 1/120
313/313 [==============================] - 9s 20ms/step - loss: 0.8948 - accuracy: 0.4995 - val_loss: 0.6941 - val_accuracy: 0.5030
Epoch 2/120
313/313 [==============================] - 5s 17ms/step - loss: 0.7024 - accuracy: 0.5007 - val_loss: 0.6934 - val_accuracy: 0.4970
Epoch 3/120
313/313 [==============================] - 5s 17ms/step - loss: 0.6958 - accuracy: 0.5030 - val_loss: 0.6946 - val_accuracy: 0.4970
Epoch 4/120
313/313 [==============================] - 5s 17ms/step - loss: 0.6952 - accuracy: 0.4997 - val_loss: 0.6931 - val_accuracy: 0.5140
Epoch 5/120
313/313 [==============================] - 5s 17ms/step - loss: 0.6948 - accuracy: 0.4965 - val_loss: 0.6935 - val_accuracy: 0.5030
Epoch 6/120
313/313 [==============================] - 5s 17ms/step - loss: 0.6953 - accuracy: 0.5016 - val_loss: 0.6932 - val_accuracy: 0.4970
Epoch 7/120
313/313 [==============================] - 5s 17ms/step - loss: 0.6941 - accuracy: 0.5001 - val_loss: 0.6935 - val_accuracy:

### 5.9 Save the Model

/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  layer_config = serialize_layer_fn(layer)


# 5.10 Evaluate on the test data

In [ ]:
# Use predict

# Step 6: Add your own content and then test the build model