**Deep Learning - CSE4006**
# LAB 1

> ## Name: **K CHARVI**
> ## Reg No: 19BCE7002
> ## Date: 18|10|2021
> ## Submitted To: Dr. BKSP Kumarraju Alluri


# Basics

**Even or Odd**

In [ ]:
num = int(input("Enter a number: "))  
if (num % 2) == 0:  
   print("{0} is Even number".format(num))  
else:  
   print("{0} is Odd number".format(num))  

Enter a number: 23
23 is Odd number


In [ ]:
import torch

In [ ]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
torch.rand(3,2)

tensor([[0.9267, 0.6597],
        [0.0560, 0.9790],
        [0.3235, 0.7738]])

In [ ]:
p=torch.tensor([[4,5],[6,7],[8,9]])

In [ ]:
p.size()

torch.Size([3, 2])

In [ ]:
p[:,1]

tensor([5, 7, 9])

In [ ]:
n=torch.tensor([[4,4],[2,3]])
m=torch.tensor([[1,7],[8,6]])

In [ ]:
n*m

tensor([[ 4, 28],
        [16, 18]])

In [ ]:
n+m

tensor([[ 5, 11],
        [10,  9]])

In [ ]:
n/m

tensor([[4.0000, 0.5714],
        [0.2500, 0.5000]])

In [ ]:
n-m

tensor([[ 3, -3],
        [-6, -3]])

# Gradient Descent

In [ ]:
import numpy as np

In [ ]:
%%time
for i in range(0,10):
  arr=np.random.randn(10000,10000)
  brr=np.random.randn(10000,10000)
  c=arr+brr

CPU times: user 1min 26s, sys: 1.21 s, total: 1min 28s
Wall time: 1min 28s


In [ ]:
%%time
for i in range(0,10):
  arr=torch.randn([10000,10000])
  brr=torch.randn([10000,10000])
  c=arr+brr

CPU times: user 16.8 s, sys: 78.1 ms, total: 16.9 s
Wall time: 16.9 s


In [ ]:
#Calculation of gradients
x = torch.ones([3, 2], requires_grad=True)
print(x)

y = x*x + 5
print(y)

p = torch.sum(y)
print(p)

p.backward()

print(x.grad)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor(36., grad_fn=<SumBackward0>)
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [ ]:
#GRADIENT DESCENT
x = torch.randn([20, 1], requires_grad=True)
y = 3*x - 2


w = torch.tensor([1.], requires_grad=True) 
b = torch.tensor([1.], requires_grad=True) 
print("Old w" , w)
print("Old b" , b)
y_hat = w*x + b
loss = torch.sum((y_hat - y)**2)
print(loss)

loss.backward()

print(w.grad, b.grad)

Old w tensor([1.], requires_grad=True)
Old b tensor([1.], requires_grad=True)
tensor(202.9072, grad_fn=<SumBackward0>)
tensor([-25.6266]) tensor([118.1871])


# Question 1

In [ ]:
# Prereq: You should use only torch library

# Step 1: Initialize w and b to random values

# Step 2: Assume you have 10000 x values and you have to predict corresponding y. #Consider the true f(x) as y=3*x-2

# Step 3: Calculate predicted y as w*x + b

# Step 4: Calculate Squared Error Loss

# Step 5: Calculate dL/dw and dL/db

# Step 6: Update w and b using the basic gradient descent algorith

# Note: Put Lines from Step 2 to Step 6 in a loop



In [ ]:
w = torch.tensor([1.], requires_grad=True) 
b = torch.tensor([1.], requires_grad=True) 

x = torch.randn([10000, 1], requires_grad=True)
y = 3*x - 2
 
y_hat = w*x + b
 
loss = torch.sum((y_hat - y)**2)
print(loss)

loss.backward()
 
with torch.no_grad(): 
  w -= 0.01 * w.grad
  b -= 0.01 * b.grad


tensor(131413.2969, grad_fn=<SumBackward0>)


In [ ]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True) 
b = torch.tensor([1.], requires_grad=True) 


print(w.item(), b.item()) 

for i in range(10000):

  x = torch.randn([1, 1]) 
  y = 3*x - 2 

  
  y_hat = w*x + b
  loss = torch.sum((y_hat - y)**2)
  
  loss.backward() 
  
  with torch.no_grad(): 
    w -= learning_rate * w.grad 
    #b gradient 
    b -= learning_rate * b.grad
    
    # w.grad.zero_() 
    # b.grad.zero_()

print(w.item(), b.item())

1.0 1.0
-7.030817135631515e+29 1.05006329551071e+30
